# Generated by Django 3.2.9 on 2021-11-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tidbyt_device', '0001_initial'),
        ('tidbyt_feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TidbytInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tidbyt_device.tidbytdevice')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tidbyt_feature.tidbytfeature')),
            ],
        ),
    ]
