# Generated by Django 4.0 on 2022-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidbyt_installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidbytinstallation',
            name='installation_status',
            field=models.CharField(choices=[('IN', 'Installed'), ('UN', 'Uninstalled'), ('PI', 'Pending Install'), ('PU', 'Pending Uninstall')], default='UN', max_length=2),
        ),
    ]
