# Generated by Django 4.0 on 2022-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidbyt_feature', '0002_rename_image_field_tidbytfeature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tidbytfeature',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
